// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMQ-mYRUXpLb5Icc6lU98_CyNqPDbRVU',
    appId: '1:1030595336673:web:e9c9dab98a5a894fe41aa0',
    messagingSenderId: '1030595336673',
    projectId: 'flash-ca82b',
    authDomain: 'flash-ca82b.firebaseapp.com',
    storageBucket: 'flash-ca82b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjOz5PRd4CcQSbvNbNXazkFKFG0KsJRik',
    appId: '1:1030595336673:android:671b0ae200de08d1e41aa0',
    messagingSenderId: '1030595336673',
    projectId: 'flash-ca82b',
    storageBucket: 'flash-ca82b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgmEqtv73FyaMI6rne1Lnsijnl4mOfcM8',
    appId: '1:1030595336673:ios:625b942b70e38508e41aa0',
    messagingSenderId: '1030595336673',
    projectId: 'flash-ca82b',
    storageBucket: 'flash-ca82b.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgmEqtv73FyaMI6rne1Lnsijnl4mOfcM8',
    appId: '1:1030595336673:ios:625b942b70e38508e41aa0',
    messagingSenderId: '1030595336673',
    projectId: 'flash-ca82b',
    storageBucket: 'flash-ca82b.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMQ-mYRUXpLb5Icc6lU98_CyNqPDbRVU',
    appId: '1:1030595336673:web:6f8f1cfb0ab5fb96e41aa0',
    messagingSenderId: '1030595336673',
    projectId: 'flash-ca82b',
    authDomain: 'flash-ca82b.firebaseapp.com',
    storageBucket: 'flash-ca82b.firebasestorage.app',
  );
}
